In [1]:
import pandas as pd

In [2]:
import os 
work_path = os.getcwd() 
raw_path = work_path + "\\raw"
processed_path = work_path + "\\processed"

In [4]:
df = pd.read_csv(raw_path+"\\kddcup.data.gz", compression='gzip', header=None,
                 sep=',', quotechar='"', error_bad_lines=False)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.0,0.0,0.0,0.0,0.0,normal.

In [6]:
df_sig = ["duration",
          "protocol_type",
          "service",
          "flag",
          "src_bytes",
          "dst_bytes",
          "land",
          "wrong_fragment",
          "urgent",
          "hot",
          "num_failed_logins",
          "logged_in",
          "num_compromised",
          "root_shell",
          "su_attempted",
          "num_root",
          "num_file_creations",
          "num_shells",
          "num_access_files",
          "num_outbound_cmds",
          "is_host_login",
          "is_guest_login",
          "count",
          "srv_count",
          "serror_rate",
          "srv_serror_rate",
          "rerror_rate",
          "srv_rerror_rate",
          "same_srv_rate",
          "diff_srv_rate",
          "srv_diff_host_rate",
          "dst_host_count",
          "dst_host_srv_count",
          "dst_host_same_srv_rate",
          "dst_host_diff_srv_rate",
          "dst_host_same_src_port_rate",
          "dst_host_srv_diff_host_rate",
          "dst_host_serror_rate",
          "dst_host_srv_serror_rate",
          "dst_host_rerror_rate",
          "dst_host_srv_rerror_rate",
          "class"]

In [7]:
df.shape, len(df_sig)

((4898431, 42), 42)

In [8]:
df.columns = df_sig
df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'class'],
      dtype='object')

In [9]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.0,0.0,0.0,0.0,0.0,normal.

In [10]:
df.to_csv(processed_path+"\\kddcup99.csv", header=True, index=None)

KeyboardInterrupt: