In [1]:
import pandas as pd

In [2]:
import os 
work_path = os.getcwd() 
raw_path = work_path + "\\raw"
processed_path = work_path + "\\processed"

In [3]:
from scipy.io.arff import loadarff
import pandas as pd

data = loadarff(raw_path+"\\file7a97574fa9ae.arff")
df = pd.DataFrame(data[0])
df.head()

,class,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
0,b'1',234.0,120.0,254.0,3260.0,70.0,1604.0,3397.0,8.0,2377.0,...,223.0,171.0,229.0,4406.0,3594.0,0.0,225.0,316.0,60.0,129.0
1,b'0',228.0,-9.0,251.0,876.0,164.0,3971.0,2991.0,7.0,2042.0,...,199.0,223.0,227.0,2107.0,3980.0,2.0,242.0,66.0,76.0,149.0
2,b'0',229.0,0.0,226.0,2765.0,39.0,3583.0,2766.0,10.0,842.0,...,201.0,187.0,221.0,4478.0,2297.0,0.0,218.0,113.0,175.0,131.0
3,b'0',248.0,45.0,221.0,4865.0,16.0,1031.0,2390.0,23.0,1104.0,...,254.0,225.0,193.0,937.0,1187.0,234.0,186.0,23.0,99.0,121.0
4,b'0',229.0,16.0,226.0,918.0,299.0,3488.0,2131.0,6.0,911.0,...,232.0,226.0,203.0,4568.0,1465.0,1.0,238.0,21.0,234.0,174.0

In [4]:
df.shape

(5124, 21)

In [5]:
df.to_csv(processed_path+"\\sylvine.csv", header=True, index=None)